version: '3.8'

services:
  iwork:
    build: .
    container_name: DKT_iwork
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ${IWORK_ENV_FILE:-iwork/.env}
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    networks:
      - dkt-net

networks:
  dkt-net:
    external: true
    name: docker_dkt-net
