# Generated by Django 5.2.13 on 2026-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalPytckreg3",
            fields=[
                (
                    "TicketNo",
                    models.CharField(
                        max_length=13,
                        primary_key=True,
                        serialize=False,
                        verbose_name="票号",
                    ),
                ),
                ("SeqNo", models.IntegerField(default=0, verbose_name="序号")),
                (
                    "WrkOrder",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="工单号"
                    ),
                ),
                ("BundleNo", models.IntegerField(default=0, verbose_name="扎号")),
                ("StepNo", models.IntegerField(default=0, verbose_name="工序号")),
                ("Qty", models.IntegerField(default=0, verbose_name="数量")),
                (
                    "RegPerSysID",
                    models.IntegerField(default=0, verbose_name="登记人系统ID"),
                ),
                (
                    "RegDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="登记日期"
                    ),
                ),
                (
                    "RegTime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="登记时间"
                    ),
                ),
                (
                    "RFID",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="RFID"
                    ),
                ),
                (
                    "Flow",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="流程"
                    ),
                ),
                (
                    "PO",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="PO号"
                    ),
                ),
                ("TimeCost", models.IntegerField(default=0, verbose_name="耗时")),
                (
                    "SysSource",
                    models.CharField(default="", max_length=3, verbose_name="系统来源"),
                ),
                (
                    "AccBundleNo",
                    models.IntegerField(default=0, verbose_name="累计扎号"),
                ),
                (
                    "MtrType",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="物料类型"
                    ),
                ),
                (
                    "Color",
                    models.CharField(
                        blank=True, default="", max_length=35, verbose_name="颜色"
                    ),
                ),
                (
                    "Sizx",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="尺码"
                    ),
                ),
                (
                    "SerialNum",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="序列号"
                    ),
                ),
                (
                    "StationID",
                    models.CharField(
                        blank=True, default="", max_length=3, verbose_name="工位ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "本地打卡记录",
                "verbose_name_plural": "本地打卡记录",
                "db_table": "pytckreg3",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pytckreg3",
            fields=[
                (
                    "TicketNo",
                    models.CharField(
                        max_length=13,
                        primary_key=True,
                        serialize=False,
                        verbose_name="票号",
                    ),
                ),
                ("SeqNo", models.IntegerField(default=0, verbose_name="序号")),
                (
                    "WrkOrder",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="工单号"
                    ),
                ),
                ("BundleNo", models.IntegerField(default=0, verbose_name="扎号")),
                ("StepNo", models.IntegerField(default=0, verbose_name="工序号")),
                ("Qty", models.IntegerField(default=0, verbose_name="数量")),
                (
                    "RegPerSysID",
                    models.IntegerField(default=0, verbose_name="登记人系统ID"),
                ),
                (
                    "RegDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="登记日期"
                    ),
                ),
                (
                    "RegTime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="登记时间"
                    ),
                ),
                (
                    "RFID",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="RFID"
                    ),
                ),
                (
                    "Flow",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="流程"
                    ),
                ),
                (
                    "PO",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="PO号"
                    ),
                ),
                ("TimeCost", models.IntegerField(default=0, verbose_name="耗时")),
                (
                    "SysSource",
                    models.CharField(default="", max_length=3, verbose_name="系统来源"),
                ),
                (
                    "AccBundleNo",
                    models.IntegerField(default=0, verbose_name="累计扎号"),
                ),
                (
                    "MtrType",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="物料类型"
                    ),
                ),
                (
                    "Color",
                    models.CharField(
                        blank=True, default="", max_length=35, verbose_name="颜色"
                    ),
                ),
                (
                    "Sizx",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="尺码"
                    ),
                ),
                (
                    "SerialNum",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="序列号"
                    ),
                ),
                (
                    "StationID",
                    models.CharField(
                        blank=True, default="", max_length=3, verbose_name="工位ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "打卡记录",
                "verbose_name_plural": "打卡记录",
                "db_table": "pytckreg3",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TargetProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField(verbose_name="目标日期")),
                ("employee_id", models.CharField(max_length=50, verbose_name="员工ID")),
                ("target_qty", models.IntegerField(default=0, verbose_name="目标产量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "目标产量",
                "verbose_name_plural": "目标产量",
                "db_table": "target_production",
                "managed": True,
                "unique_together": {("target_date", "employee_id")},
            },
        ),
    ]
