# Generated by Django 5.2.15 on 2026-07-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwork', '0001_target_production'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetproduction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='targetproduction',
            name='workorder',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='工单号'),
        ),
        migrations.AlterUniqueTogether(
            name='targetproduction',
            unique_together={('target_date', 'employee_id', 'workorder')},
        ),
    ]
