# Generated by Django 5.2.14 on 2026-07-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwork", "0002_add_workorder_to_targetproduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=50, verbose_name="工单号")),
                (
                    "order_dept",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="工单/部门"
                    ),
                ),
                (
                    "style_no",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="款号"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="产品名称"
                    ),
                ),
                (
                    "style_desc",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="款式"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "生产工单",
                "verbose_name_plural": "生产工单",
                "db_table": "production_orders",
                "managed": True,
                "indexes": [
                    models.Index(fields=["order_no"], name="idx_po_order_no"),
                    models.Index(fields=["style_no"], name="idx_po_style_no"),
                    models.Index(fields=["order_dept"], name="idx_po_order_dept"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "order_no",
                            "order_dept",
                            "style_no",
                            "product_name",
                            "style_desc",
                        ),
                        name="idx_po_unique_record",
                    )
                ],
            },
        ),
    ]
