# Generated by Django 5.2.14 on 2026-07-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iwork", "0003_productionorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pydefstp",
            fields=[
                (
                    "StepNo",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="工序号"
                    ),
                ),
            ],
            options={
                "verbose_name": "工序定义",
                "verbose_name_plural": "工序定义",
                "db_table": "pydefstp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pywrkstp",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "WrkOrder",
                        "StepNo",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("StepNo", models.IntegerField(default=0, verbose_name="工序号")),
                (
                    "WrkOrder",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="工单号"
                    ),
                ),
                (
                    "Description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        null=True,
                        verbose_name="工序描述",
                    ),
                ),
                ("StepTime", models.FloatField(default=0.0, verbose_name="标准工时")),
            ],
            options={
                "verbose_name": "工单工序工时",
                "verbose_name_plural": "工单工序工时",
                "db_table": "pywrkstp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(unique=True, verbose_name="快照日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "同步中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "source_row_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="源记录数"),
                ),
                (
                    "source_total_qty",
                    models.BigIntegerField(default=0, verbose_name="源总产量"),
                ),
                (
                    "fact_row_count",
                    models.PositiveIntegerField(default=0, verbose_name="事实行数"),
                ),
                (
                    "metadata_row_count",
                    models.PositiveIntegerField(default=0, verbose_name="元数据行数"),
                ),
                (
                    "missing_metadata_count",
                    models.PositiveIntegerField(default=0, verbose_name="缺失元数据数"),
                ),
                (
                    "snapshot_version",
                    models.PositiveIntegerField(default=1, verbose_name="快照版本"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "db_table": "historical_sync_state",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProductionFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_date", models.DateField(verbose_name="生产日期")),
                (
                    "event_hour",
                    models.SmallIntegerField(default=-1, verbose_name="生产小时"),
                ),
                (
                    "registered_date",
                    models.DateTimeField(db_column="RegDate", verbose_name="登记日期"),
                ),
                (
                    "registered_time",
                    models.DateTimeField(
                        blank=True,
                        db_column="RegTime",
                        null=True,
                        verbose_name="登记时间",
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="生产线"
                    ),
                ),
                (
                    "station_id",
                    models.CharField(
                        blank=True, default="", max_length=3, verbose_name="工位ID"
                    ),
                ),
                (
                    "employee_id",
                    models.IntegerField(default=0, verbose_name="员工系统ID"),
                ),
                (
                    "wrk_order",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="本厂款号"
                    ),
                ),
                ("step_no", models.IntegerField(default=0, verbose_name="工序号")),
                ("qty", models.BigIntegerField(default=0, verbose_name="聚合产量")),
                (
                    "source_record_count",
                    models.PositiveIntegerField(default=0, verbose_name="源记录数"),
                ),
            ],
            options={
                "db_table": "historical_production_fact",
                "indexes": [
                    models.Index(
                        fields=["production_date", "flow", "employee_id"],
                        name="idx_hist_flow_emp",
                    ),
                    models.Index(
                        fields=["production_date", "wrk_order", "step_no", "flow"],
                        name="idx_hist_wo_step_flow",
                    ),
                    models.Index(
                        fields=["production_date", "step_no", "employee_id"],
                        name="idx_hist_step_emp",
                    ),
                    models.Index(
                        fields=["production_date", "event_hour"],
                        name="idx_hist_date_hour",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "production_date",
                            "event_hour",
                            "flow",
                            "station_id",
                            "employee_id",
                            "wrk_order",
                            "step_no",
                        ),
                        name="uq_history_fact_grain",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalStepSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="快照日期")),
                ("wrk_order", models.CharField(max_length=14, verbose_name="本厂款号")),
                ("step_no", models.IntegerField(verbose_name="工序号")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="工序描述"
                    ),
                ),
                (
                    "step_time",
                    models.FloatField(blank=True, null=True, verbose_name="标准工时"),
                ),
                (
                    "style_no",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="款号"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="产品名称"
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="生产单号"
                    ),
                ),
            ],
            options={
                "db_table": "historical_step_snapshot",
                "indexes": [
                    models.Index(
                        fields=["snapshot_date", "wrk_order"],
                        name="idx_hist_meta_workorder",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_date", "wrk_order", "step_no"),
                        name="uq_history_step_snapshot",
                    )
                ],
            },
        ),
    ]
