# Generated by Django 5.2.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    """新增按业务日期和生产组保存的整组目标表。"""

    dependencies = [
        ('iwork', '0004_historical_production_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTargetProduction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('flow_name', models.CharField(max_length=40, verbose_name='生产组')),
                ('target_qty', models.IntegerField(default=0, verbose_name='整组目标产量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生产组目标产量',
                'verbose_name_plural': '生产组目标产量',
                'db_table': 'group_target_production',
                'managed': True,
                'unique_together': {('target_date', 'flow_name')},
            },
        ),
    ]
