# Generated by Django 5.2.5 on 2026-08-18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """新增可信身份、Flow 负责人、每日目标责任和审计模型。"""

    dependencies = [
        ('iwork', '0008_historicalstepsnapshot_initial_style_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptargetproduction',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='是否逾期提交'),
        ),
        migrations.AddField(
            model_name='grouptargetproduction',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AddField(
            model_name='grouptargetproduction',
            name='submitted_by_subject',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='提交人 subject'),
        ),
        migrations.AddField(
            model_name='grouptargetproduction',
            name='submitted_by_username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='提交人用户名'),
        ),
        migrations.CreateModel(
            name='DailyTargetObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('flow_name', models.CharField(max_length=40, verbose_name='生产组')),
                ('status', models.CharField(choices=[('pending', '待提交'), ('fulfilled', '按时完成'), ('overdue', '已逾期'), ('fulfilled_late', '逾期完成'), ('waived', '已免除')], default='pending', max_length=16, verbose_name='状态')),
                ('deadline_at', models.DateTimeField(verbose_name='截止时间')),
                ('submitted_by_subject', models.CharField(blank=True, default='', max_length=255, verbose_name='提交人 subject')),
                ('submitted_by_username', models.CharField(blank=True, default='', max_length=150, verbose_name='提交人用户名')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('waived_at', models.DateTimeField(blank=True, null=True, verbose_name='免除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={'db_table': 'daily_target_obligation'},
        ),
        migrations.CreateModel(
            name='GroupTargetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('flow_name', models.CharField(max_length=40, verbose_name='生产组')),
                ('action', models.CharField(max_length=32, verbose_name='动作')),
                ('actor_subject', models.CharField(max_length=255, verbose_name='操作人 subject')),
                ('actor_username', models.CharField(blank=True, default='', max_length=150, verbose_name='操作人用户名')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={'db_table': 'group_target_audit_log'},
        ),
        migrations.CreateModel(
            name='IworkPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, verbose_name='Keycloak subject')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='显示名称')),
                ('keycloak_groups', models.JSONField(blank=True, default=list, verbose_name='Keycloak 组')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否管理员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={'verbose_name': 'iwork 身份', 'verbose_name_plural': 'iwork 身份', 'db_table': 'iwork_principal'},
        ),
        migrations.CreateModel(
            name='TargetSubmissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(unique=True, verbose_name='生效日期')),
                ('deadline_time', models.TimeField(default=datetime.time(9, 0), verbose_name='提交截止时间')),
                ('timezone_name', models.CharField(default='Asia/Bangkok', max_length=64, verbose_name='业务时区')),
                ('created_by_subject', models.CharField(max_length=255, verbose_name='创建人 subject')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={'db_table': 'target_submission_policy', 'ordering': ['-effective_date']},
        ),
        migrations.CreateModel(
            name='ManagedFlowAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(max_length=40, verbose_name='生产组')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('expires_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('created_by_subject', models.CharField(max_length=255, verbose_name='创建人 subject')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_assignments', to='iwork.iworkprincipal', verbose_name='负责人')),
            ],
            options={'db_table': 'managed_flow_assignment'},
        ),
        migrations.CreateModel(
            name='DailyTargetObligationLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='负责人 subject')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='负责人用户名')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_links', to='iwork.dailytargetobligation', verbose_name='每日责任')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_links', to='iwork.iworkprincipal', verbose_name='负责人')),
            ],
            options={'db_table': 'daily_target_obligation_leader'},
        ),
        migrations.AddConstraint(
            model_name='dailytargetobligation',
            constraint=models.UniqueConstraint(fields=('target_date', 'flow_name'), name='uq_daily_target_obligation'),
        ),
        migrations.AddIndex(
            model_name='dailytargetobligation',
            index=models.Index(fields=['target_date', 'status'], name='idx_target_obligation_status'),
        ),
        migrations.AddIndex(
            model_name='grouptargetauditlog',
            index=models.Index(fields=['target_date', 'flow_name', 'created_at'], name='idx_group_target_audit'),
        ),
        migrations.AddConstraint(
            model_name='managedflowassignment',
            constraint=models.UniqueConstraint(fields=('principal', 'flow_name', 'effective_date'), name='uq_flow_assignment_start'),
        ),
        migrations.AddConstraint(
            model_name='managedflowassignment',
            constraint=models.CheckConstraint(condition=models.Q(('expires_date__isnull', True), ('expires_date__gte', models.F('effective_date')), _connector='OR'), name='ck_flow_assignment_dates'),
        ),
        migrations.AddIndex(
            model_name='managedflowassignment',
            index=models.Index(fields=['flow_name', 'effective_date', 'expires_date'], name='idx_flow_assignment_valid'),
        ),
        migrations.AddConstraint(
            model_name='dailytargetobligationleader',
            constraint=models.UniqueConstraint(fields=('obligation', 'principal'), name='uq_obligation_leader'),
        ),
    ]
