# Generated by Django 5.2 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    """为历史事实保存已校验的 Remark 员工 ID。"""

    dependencies = [
        ('iwork', '0010_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyperson',
            fields=[
                (
                    'SysID',
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name='人员系统ID',
                    ),
                ),
                (
                    'Remark',
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name='员工ID',
                    ),
                ),
            ],
            options={
                'db_table': 'pyperson',
                'managed': False,
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.AddField(
            model_name='historicalproductionfact',
            name='employee_remark',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='员工新ID',
            ),
        ),
    ]
