# Generated by Django 5.2.17 on 2026-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwork', '0013_backfill_iwork_admin_alert_audiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsubmissionpolicy',
            name='timezone_name',
            field=models.CharField(default='Asia/Yangon', max_length=64, verbose_name='业务时区'),
        ),
    ]
